# Generated by Django 5.0.6 on 2024-06-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/photos/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
